server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: faq-manager
          uri: http://localhost:8081
          predicates:
            - Path=/api/faqmanager/**