version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: faqmanager-postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: faqmanager-pgadmin
    restart: always
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@example.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata: